const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
require('./calculator.js');
const {parseAmount, allocate, validPercentages, defaults} = globalThis.MoneyCalculator;
assert.equal(parseAmount('17 350,50'), 1735050);
assert.equal(parseAmount(''), 0);
assert.equal(parseAmount('0,01'), 1);
assert.equal(parseAmount('1000000000'), 100000000000);
for (const invalid of ['-1','1.234','1e3','abc','1,2,3','1000000000.01']) assert.equal(parseAmount(invalid), null);
for (const invalid of [[35,40,10,14],[35.5,39.5,10,15],[-1,41,10,50],[99,0,0],null]) assert.equal(validPercentages(invalid), false);
assert.deepEqual(allocate(1735000, defaults), [607250,694000,173500,260250]);
assert.deepEqual(allocate(1, [25,25,25,25]), [1,0,0,0]);
assert.deepEqual(allocate(100, [0,100,0,0]), [0,100,0,0]);
for (const percentages of [defaults,[25,25,25,25],[0,0,0,100],[1,2,3,94]]) {
  for (let cents = 0; cents < 10000; cents++) {
    const values = allocate(cents, percentages);
    assert.equal(values.reduce((a,b) => a+b,0), cents);
    values.forEach((v,i) => { assert.ok(Number.isInteger(v) && v >= 0); assert.ok(Math.abs(v-cents*percentages[i]/100) < 1); });
  }
  assert.equal(allocate(100000000000, percentages).reduce((a,b) => a+b,0), 100000000000);
}
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.webmanifest'),'utf8'));
for (const icon of manifest.icons) assert.ok(fs.existsSync(path.join(__dirname,icon.src)));
const worker = fs.readFileSync(path.join(__dirname,'sw.js'),'utf8');
const assets = worker.match(/const ASSETS = (\[.*\]);/)[1];
for (const asset of JSON.parse(assets.replace(/'/g,'"'))) assert.ok(fs.existsSync(path.join(__dirname,asset)));
console.log('PASS: input, validation, 40,000 allocations, limits, manifest and offline assets.');
require('./ledger.js');
const {periodBounds,parseDate,validEntry,summarize} = globalThis.MoneyLedger;
const now = new Date(2026,9,7,15);
assert.equal(parseDate('2026-02-30'),null);
assert.equal(parseDate('2024-02-29').getDate(),29);
assert.equal(periodBounds('7',now).start.getDate(),1);
assert.equal(periodBounds('month',now).start.getMonth(),9);
assert.equal(periodBounds('previous',new Date(2026,0,3)).start.getFullYear(),2025);
assert.equal(periodBounds('previous',new Date(2026,0,3)).start.getMonth(),11);
assert.equal(periodBounds('year',now).start.getMonth(),0);
assert.equal(periodBounds('custom',now,'2026-10-08','2026-10-07'),null);
assert.equal(periodBounds('custom',now,'2026-10-01','2026-10-07').end.getDate(),8);
const legacy = {cents:100000,createdAt:now.getTime(),percentages:defaults,amounts:allocate(100000,defaults)};
const expense = {type:'expense',cents:50000,category:1,note:'Продукты',createdAt:now.getTime()};
assert.ok(validEntry(legacy)); assert.ok(validEntry(expense));
assert.equal(validEntry({...expense,category:4}),false);
assert.equal(validEntry({...legacy,type:'unknown'}),false);
const totals = summarize([legacy,expense]);
assert.equal(totals.totalIncome,100000); assert.equal(totals.totalExpenses,50000);
assert.equal(totals.net,50000); assert.equal(totals.income[1]-totals.expenses[1],-10000);
console.log('PASS: calendar periods, leap days, legacy history, expenses and negative category remainder.');

require('./finance.js');require('./store.js');
const {payoff,debtPlan,distributeShare}=globalThis.MoneyFinance;
assert.deepEqual(payoff(100000,0,10000),{months:10,interest:0,total:100000});
assert.deepEqual(payoff(100000,0,200000),{months:1,interest:0,total:100000});
assert.deepEqual(payoff(0,20,0),{months:0,interest:0,total:0});
assert.equal(payoff(100000,12,1000).reason,'insufficient');
assert.equal(payoff(100000,0,0).reason,'insufficient');
const estimate=payoff(100000,12,10000);assert.equal(estimate.months,11);assert.ok(estimate.interest>0);assert.equal(estimate.total,100000+estimate.interest);
const debt={id:'loan',name:'Кредит',type:'loan',balance:100000,apr:12,minimum:1000,payment:10000};
assert.equal(debtPlan([debt],100000).percent,10);
assert.equal(debtPlan([debt],30000).percent,34);
assert.equal(debtPlan([debt],0).percent,null);
assert.equal(globalThis.MoneyFinance.validDebt({...debt,type:'personal',apr:12}),false);
const cfg=MoneyStore.defaultConfig();assert.ok(MoneyStore.validConfig(cfg));
const noDebt=distributeShare(cfg.categories,'debt',0);assert.equal(noDebt[0].enabled,false);assert.equal(noDebt.reduce((sum,item)=>sum+item.percent,0),100);
const fifty=distributeShare(cfg.categories,'debt',50);assert.equal(fifty[0].percent,50);assert.equal(fifty.reduce((sum,item)=>sum+item.percent,0),100);
assert.throws(()=>distributeShare(cfg.categories,'debt',101));
assert.equal(MoneyStore.validConfig({...cfg,categories:[...cfg.categories,{...cfg.categories[0]}]}),false);
const modern={schema:2,type:'income',cents:1000,createdAt:now.getTime(),allocations:[{categoryId:'new',name:'Новая',percent:100,cents:1000}]};assert.ok(validEntry(modern));
const mixed=MoneyLedger.summarizeCategories([legacy,expense,modern],cfg.categories);
assert.equal(mixed.totalIncome,101000);assert.equal(mixed.totalExpenses,50000);assert.equal(mixed.categories.find(item=>item.id==='new').income,1000);
assert.equal(MoneyLedger.normalize(legacy).allocations[0].categoryId,'debt');
assert.equal(validEntry({...modern,allocations:[{...modern.allocations[0],cents:999}]}),false);
for(const p of [[100],[10,20,30,20,20],[0,0,0,0,0,0,0,0,0,0,0,100]])assert.equal(allocate(1735001,p).reduce((a,b)=>a+b,0),1735001);
console.log('PASS: variable categories, legacy normalization, settings validation, amortization, debt allocation and no-debt scenario.');

assert.equal(MoneyStore.validConfig({...cfg,categories:[null]}),false);assert.equal(MoneyStore.validConfig({...cfg,debts:[null]}),false);assert.equal(validEntry({...modern,allocations:[null]}),false);

require('./extras-store.js');
const extra=MoneyExtras.defaultExtras();assert.ok(MoneyExtras.validExtras(extra));
const withGoal={...extra,goals:[{id:'goal',name:'Подушка',target:100000,saved:25000,deadline:''}]};assert.ok(MoneyExtras.validExtras(withGoal));assert.equal(MoneyExtras.validExtras({...withGoal,goals:[{...withGoal.goals[0],target:0}]}),false);
const fullBackup={format:'potok-backup',version:1,config:cfg,extras:withGoal,entries:[{...legacy,id:1}]};assert.ok(MoneyExtras.validBackup(fullBackup));assert.equal(MoneyExtras.validBackup({...fullBackup,version:2}),false);assert.equal(MoneyExtras.validBackup({...fullBackup,entries:[{...legacy,id:1},{...legacy,id:1}]}),false);assert.equal(MoneyExtras.validBackup({...fullBackup,extras:{}}),false);
console.log('PASS: goals, templates and complete backup validation.');
